apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-instantiate-template
spec:
  params:
  - name: TEMPLATE
    type: string
  - name: PARAMS
    type: string
  steps:
    - name: instantiate-template
      image: quay.io/openshift/origin-cli:latest
      script: |
        oc process $(params.TEMPLATE) $(params.PARAMS) | oc create -f -