apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tkn
spec:
  params:
  - name: tkn-image
    description: tkn CLI container image to run this task
    default: gcr.io/tekton-releases/dogfooding/tkn
  - name: ARGS
    type: array
    description: tkn CLI arguments to run
  steps:
    - name: tkn
      image: "$(params.tkn-image)"
      command: ["/usr/local/bin/tkn"]
      args: ["$(params.ARGS)"]