apiVersion: broker.amq.io/v2alpha5
kind: ActiveMQArtemis
metadata:
  name: amq-mqtt
  annotations:
    app.openshift.io/connects-to: >-
      [{"apiVersion":"apps/v1","kind":"Deployment","name":"device-registry"},{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"iot-consumer"},{"apiVersion":"apps/v1","kind":"Deployment","name":"ntt-device-registry"}]
  labels:
    app.kubernetes.io/part-of: {{ .Values.appGrouping }}
    app: {{ .Values.appLabel }}
spec:
  acceptors:
    - expose: true
      name: all
      port: 61616
      {{- if .Values.amqBroker.tlsEnable }}
      sslEnabled: true
      sslSecret: {{ .Values.amqBroker.tlsSecretName }}
      verifyHost: false {{ end }}
    - expose: true
      name: mqtt
      port: 1883
      protocols: mqtt
  adminPassword: {{ .Values.amqBroker.password }}
  adminUser: {{ .Values.amqBroker.user }}
  addressSettings: {}
  console:
    expose: true
  deploymentPlan:
    size: 1
    podSecurity: {}
    resources: {}
    readinessProbe: {}
    messageMigration: false
    extraMounts: {}
    managementRBACEnabled: true
    livenessProbe: {}
    journalType: aio
    enableMetricsPlugin: true
    storage: {}
  upgrades:
    enabled: false
    minor: false
  version: 7.9.1

