apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-consumer-cfg
data:
  MQTT_BROKER: 'ws://broker-amq-mqtt-all-0-svc:61616'
  MQTT_PASSWORD: iotuser
  MQTT_USER: iotuser
  PORT: '3000'
  SOCKET_PATH: /api/service-web/socket
  TEMPERATURE_THRESHOLD: '70.0'
  TOPIC_GPS: iot-sensor/sw/gps
  TOPIC_TEMPERATURE: iot-sensor/sw/temperature
  TOPIC_VIBRATION: iot-sensor/sw/vibration
  TOPIC_LIGHT: iot-sensor/sw/light
  TEMPERATURE_ALERT_ENABLED: 'false'
  VIBRATION_ALERT_ENABLED: 'true'
  VIBRATION_ANOMALY_ENABLED: 'true'
  ANOMALY_DETECTION_URL: 'http://anomaly-detection-predictor:8000'


