apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: iot-consumer
  name: iot-consumer
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output:
    to:
      kind: ImageStreamTag
      name: iot-consumer:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/sa-mw-dach/manuela-dev.git
    type: Git
    contextDir: "components/iot-consumer"
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nodejs:10'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
  - imageChange:
    type: ImageChange
status: 
  lastVersion: 0
