apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-consumer-cfg
data:
  MQTT_BROKER: 'ws://amq-mqtt-mqtt-0-svc:1883'
  MQTT_PASSWORD: iotuser
  MQTT_USER: iotuser
  PORT: '3000'
  SOCKET_PATH: /api/service-web/socket
  TEMPERATURE_THRESHOLD: '70.0'
  TOPIC_GPS: iot-sensor/sw/gps
  TOPIC_TEMPERATURE: iot-sensor/sw/temperature
  TOPIC_VIBRATION: iot-sensor/sw/vibration
  TOPIC_LIGHT: iot-sensor/sw/light
  TOPIC_NTT_VALUES: MSAPValue
  TOPIC_NTT_ALARM: MSAPAlarm
  TEMPERATURE_ALERT_ENABLED: 'false'
  VIBRATION_ALERT_ENABLED: 'false'
  VIBRATION_ANOMALY_ENABLED: 'false'
  ANOMALY_DETECTION_URL: 'http://anomaly-detection-predictor:8000'


