kind: Service
apiVersion: v1
metadata:
  name: mongo
spec:
  ports:
    - name: 27017-tcp
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
    deploymentconfig: mongo
  type: ClusterIP
  sessionAffinity: None
