apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-all
spec:
  tasks:
  - name: sensor-broker-test
    taskRef:
      name: mock
      kind: Task
    params:
      - name: MESSAGE
        value: "succesfully sent messages to broker..."
  - name: consumer-broker-test
    taskRef:
      name: mock
      kind: Task
    params:
      - name: MESSAGE
        value: "succesfully processed messages from broker..."
  - name: consumer-frontend-test
    taskRef:
      name: mock
      kind: Task
    params:
      - name: MESSAGE
        value: "succesfully executed Websocket APIs..."
  - name: e2e-test
    taskRef:
      name: mock
      kind: Task
    runAfter:
      - sensor-broker-test
      - consumer-broker-test
      - consumer-frontend-test
    params:
      - name: MESSAGE
        value: "e2e testsuite succesfully executed"
  # - name: fail
  #   taskRef:
  #     name: fail
  #     kind: Task
  #   runAfter:
  #   - e2e-test