apiVersion: v1
kind: Template
metadata:
  name: build-iot-anomaly-detection
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: build-and-test-iot-anomaly-detection-
  spec:
    pipelineRef:
      name: build-and-test
    workspaces:
    - name: config
      configMap:
        name: environment
    - name: github-secret
      secret:
        secretName: github
    - name: argocd-env-secret
      secret:
        secretName: argocd-env
    - name: build-artifacts
      persistentVolumeClaim:
        claimName: build-artifacts
    - name: gitrepos
      # volumeClaimTemplate:
      #   spec:
      #     accessModes: 
      #     - ReadWriteMany
      #     resources:
      #       requests:
      #         storage: 1Gi
      persistentVolumeClaim:
        claimName: iot-anomaly-detection
    params:
    - name: S2I_BUILDER_IMAGE
      value: registry.access.redhat.com/rhscl/python-36-rhel7
    - name: LOCAL_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/anomaly-detection
    - name: PATH_CONTEXT
      value: components/iot-anomaly-detection
    - name: COMPONENT_NAME
      value: iot-anomaly
    - name: CONFIGMAP_PREFIX
      value: IOT_ANOMALY