apiVersion: v1
kind: Template
metadata:
  name: build-image-pushprox
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: build-image-pushprox-
  spec:
    pipelineRef:
      name: build-images
    workspaces:
    - name: config
      configMap:
        name: environment
    - name: github-secret
      secret:
        secretName: github
    - name: quay-secret
      secret:
        secretName: quay-build-secret
    - name: gitrepos
      # volumeClaimTemplate:
      #   spec:
      #     accessModes: 
      #     - ReadWriteMany
      #     resources:
      #       requests:
      #         storage: 1Gi
      persistentVolumeClaim:
        claimName: build-images
    params:
    - name: PATH_CONTEXT
      value: tekton/images/pushprox
    - name: OUTPUT_IMAGE_CONFIGMAPKEY
      value: PUSHPROX_REMOTE_IMAGE
    - name: DEV_REVISION 
      value: pushprox