apiVersion: v1
kind: Template
metadata:
  name: build-iot-software-sensor-quarkus
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: build-and-test-iot-software-sensor-quarkus-
  spec:
    pipelineRef:
      name: build-and-test
    workspaces:
    - name: config
      configMap:
        name: environment
    - name: github-secret
      secret:
        secretName: github
    - name: argocd-env-secret
      secret:
        secretName: argocd-env
    - name: build-artifacts
      persistentVolumeClaim:
        claimName: build-artifacts
    - name: gitrepos
      # volumeClaimTemplate:
      #   spec:
      #     accessModes: 
      #     - ReadWriteMany
      #     resources:
      #       requests:
      #         storage: 1Gi
      persistentVolumeClaim:
        claimName: iot-software-sensor
    params:
    - name: S2I_BUILDER_IMAGE
      value: quay.io/quarkus/ubi-quarkus-native-s2i:19.3.1-java11
    - name: LOCAL_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/manuela-tst-all/machine-sensor
    - name: PATH_CONTEXT
      value: components/iot-software-sensor-quarkus
    - name: COMPONENT_NAME
      value: iot-swsensor
    - name: CONFIGMAP_PREFIX
      value: IOT_SWSENSOR