apiVersion: v1
kind: Secret
metadata:
  name: firewall-inventory
type: Opaque 
data: {}
stringData: 
  hostname: firewall.hostname.example.com
  ansible_user: root
  privatekey: |+
    -----BEGIN OPENSSH PRIVATE KEY-----
    ... PASTE PRIVATE KEY HERE ...
    -----END OPENSSH PRIVATE KEY-----