apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- iot-consumer/manifests
- iot-frontend/manifests
- iot-software-sensor/manifests
# - iot-software-sensor-quarkus/manifests
- iot-mqtt2kafka-integration/manifests
- iot-kafka2S3-integration/manifests

# Open data hub is optional
- iot-anomaly-detection/manifests

# Monitoring is optional (really?)
- iot-monitoring/manifests
