apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  #change the name to match the cluster name this 
  #argocd agent is responsible for
  name: cluster1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    #change the repoURL to point to your gitops repo
    repoURL: https://github.com/<organisation>/<repo>.git
    targetRevision: HEAD
    #change the path to point to the directory in the gitops repo
    #that represents the execution environment
    path: deployment/execenv-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
