apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    seldon-app: anomaly-detection-predictor
  name: manuela-seldon
spec:
  endpoints:
  - interval: 30s
    path: /prometheus
    port: http
  selector:
    matchLabels:
      seldon-app: anomaly-detection-predictor
