{
 "title": "Prediction Analytics Manuela AIO",
 "description": "Based Prediction Analytics Helm. Modified for 1.2.2. Seldon Operator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "deployment",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,deployment_name)"
   },
   {
    "name": "predictor",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,predictor_name)"
   },
   {
    "name": "version",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,predictor_version)"
   },
   {
    "name": "model_name",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_name)"
   },
   {
    "name": "model_image",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_image)"
   },
   {
    "name": "model_version",
    "query": "label_values(seldon_api_executor_client_requests_seconds_count,model_version)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sensor data",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "iot_anomaly_actual" }
   ]
  },
  {
   "title": "Anomaly Predictions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "iot_anomaly_prediction" }
   ]
  },
  { "title": "Heading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Seldon Core API Dashboard</span>\n</div>"
  },
  { "title": "Global Counts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Global Request Rate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_executor_server_requests_seconds_count[1m])),0.001)"
    }
   ]
  },
  {
   "title": "Success",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_server_requests_seconds_count{status!~\"5.*\"}[1m])) / sum(rate(seldon_api_executor_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Success ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\",status!~\"5.*\"}[1m])) / sum(rate(seldon_api_executor_client_requests_seconds_count{deployment_name=~\"$deployment\"}[1m]))"
    }
   ]
  },
  {
   "title": "Request Rate ($deployment)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "round(sum(irate(seldon_api_executor_client_requests_seconds_count{deployment_name=~'$deployment'}[1m])), 0.001)"
    }
   ]
  },
  { "title": "Models", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "content": "<div class=\"text-center dashboard-header\">\n  <span>Models</span>\n</div>"
  },
  { "title": "Model Metrics $model_image", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "model_image" },
  {
   "title": "Reqs/sec to $model_image",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{model_name=~\"$model_name\",model_version=~\"$model_version\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (model_name,predictor_name,predictor_version,model_image,model_version,service)",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} ({{model_name}} {{model_image}} : {{model_version}}) {{service}}"
    }
   ]
  },
  {
   "title": "Reqs/sec to $model_image",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(seldon_api_executor_client_requests_seconds_count{model_name=~\"$model_name\",model_version=~\"$model_version\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\"}[1m])) by (model_name,predictor_name,predictor_version,model_image,model_version,service)"
    }
   ]
  },
  {
   "title": "$model_image Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}: {{model_version}} (p50)"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p75)"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version, service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}}  {{service}} (p90)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(seldon_api_executor_client_requests_seconds_bucket{exported_service=~\".*[Pp]redict\",model_image=~\"$model_image\",predictor_name=~\"$predictor\",predictor_version=~\"$version\",model_name=~\"$model_name\",model_version=~\"$model_version\"}[1m])) by (predictor_name,predictor_version,model_name,model_image,model_version,service,le))",
     "legendFormat": "{{predictor_name}}:{{predictor_version}} {{model_name}} {{model_image}}:{{model_version}} {{service}} (p99)"
    }
   ]
  }
 ]
}