apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
spec:
  port:
    targetPort: web
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  wildcardPolicy: None
status: {}
